version: '3'

services:
  nginx-cdm:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8876:80"
    depends_on:
      - app
    container_name: nginx-cdm
    networks:
      - cdm

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
    container_name: app
    networks:
      - cdm
  
  mysql:
    image: mysql/mysql-server:8.0.23
    restart: unless-stopped
    volumes:
      - ./deploy/mysql:/docker-entrypoint-initdb.d
    environment:
        MYSQL_DATABASE: change_detection_machine
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: 1234
        MYSQL_USER: cdm
        MYSQL_INITDB_ARGS: --max_allowed_packet=128M
    ports:
      - 8101:3306
    networks:
      - cdm
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: mysql

networks:
  cdm:
    driver: bridge