import os
from dotenv import load_dotenv

load_dotenv()

STORAGE_CONNECTION = os.getenv("STORAGE_CONNECTION")
YANDEX_CLOUD_KEY = os.getenv("YANDEX_CLOUD_KEY")
YANDEX_CLOUD_SECRET = os.getenv("YANDEX_CLOUD_SECRET")
YANDEX_CLOUD_ENDPOINT = os.getenv("YANDEX_CLOUD_ENDPOINT")
YANDEX_CLOUD_REGION = os.getenv("YANDEX_CLOUD_REGION")
YANDEX_CLOUD_BUCKET = os.getenv("YANDEX_CLOUD_BUCKET")
YANDEX_CLOUD_URL = os.getenv("YANDEX_CLOUD_URL")
