version: '3'

services:
  python_service:
    build:
      context: .
      dockerfile: _docker/python_service/Dockerfile
    network_mode: bridge
    ports:
      - "8123:8123"
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8123"
    # env_file:
    #   - .env
    volumes:
      - ./:/var/www/python_service
    container_name: python_service