version: '3'

services:
  python_service:
    build:
      context: .
      dockerfile: _docker/python_service/Dockerfile
    ports:
      - "8123:8123"
    volumes:
      - .:/var/www/python_service
    container_name: python_service
    networks:
      laravel_cdm:
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8123"

networks:
  laravel_cdm:
    external: true